language: node_js

os:
  - linux
  - osx

node_js:
  - node

stages:
  - lint
  - unit
  - test
  - name: deploy
    if: branch = travis-auto-build-release

jobs:
  include:
  - stage: lint
    script: npm run lint
  - stage: unit
    script: npm run test:unit
  - stage: test
    script: scripts/checked-timeout 60 xvfb-run npx --no-install vue-cli-service electron:serve
  - stage: deploy
    script:
      - npm run electron:generate-icons
      - npm run electron:build

script: skip

matrix:
  include:
    - os: osx
      osx_image: xcode10.2
      language: node_js
      node_js: "10"
      env:
        - ELECTRON_CACHE=$HOME/.cache/electron
        - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
      script:
        - npm run electron:generate-icons
        - npm run electron:build

    - os: linux
      services: docker
      language: generic

deploy:
  provider: releases
  skip_cleanup: true
  api_key: "$GITHUB_TOKEN"
  file_glob: true
  file:
  - dist_electron/*.AppImage
  - dist_electron/*.dmg
  on:
    tags: true
    stage: deploy
    branch: travis-auto-build-release


env:
  global:
    secure: cpyX4rAxApGy7c20ZInazQDKXpUgpmUcN6jWJGHxWxEbvYHEPrnBTjEapSHrYB/Q9Svwku045rV7HTxlGNSlt985ejJ+QHRd7qofc8EDmwTXGysAx/XVbWP9fBF96H27ErBlNq3Sd2ct26zubRmJd7Mpv73E3ndFl/BvO/d8BuUv8WET6a2/uRRrPuJVpCc9zOe3/5paPsG4bIcxQhzSzpLnrQG9IzCXi/5s3xCYr07/rp8BI6ojwTpQ/aUOtd5how7EzM3Ce0CREZxTjN33IH47j8DZLl1f4MhzPTtxtdeKUEEelqy67EErfb2Jcf0u098QtWSG/Sp+0dZOZm4IiiLBs+qqw1sXGgVGieq5AFmq70yZ3CyD1aIKukYVJxbDSK55kjMnheDmdCdass4+LRQ4VezdfrYXlQ2zM4/y3xympAn2ysfDb4XxbvcicvPEiPumtwVfr3WPbLGGqlb69rVJwna4MzefySDXzU15fbVs62iQyB6TLlA0aUNjPI3ocxTNkeR0Yu0WvQDsr6D9RZsHyq7SjtUiDHfJxE4KXSRTjsYUICueOCDQBDUxXIqPEDg9dZSEP0Nt6fa7940DryqJ93QZl8IwRgKPkB7A//XmCnKBE6yq9F1SWwxNuDEHzj5MF4y+XYWjT8+r3xXvo6G45LqFOwlhP4SvepNhZNo=
