name: build-release
on: [push]

jobs:
  lint-test-run:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    name: Lint the sources and run unit tests
    steps:
      - uses: actions/checkout@v2
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: small-npm-deps-${{ hashFiles('**/package-lock.json') }}-${{ matrix.os }}
          restore-keys: small-npm-deps-
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm ci
      - name: Generate icons
        run: npm run electron:generate-icons
      - name: Build it
        run: npm run electron:build
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          path: |
            dist_electron/*.AppImage
            dist_electron/*.exe
            dist_electron/*.dmg
          retention-days: 5
          if-no-files-found: error
